export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST' // 请求话题列表
export const FETCH_TOPIC_REQUEST = 'FETCH_TOPIC_REQUEST' // 请求话题文章
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST' // 请求用户
export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST' // 请求登录
export const LOGIN_OUT = 'LOGIN_OUT' // 退出
export const FETCH_COLLECT_REQUEST = 'FETCH_COLLECT_REQUEST' // 话题收藏
export const FETCH_DE_COLLECT_REQUEST = 'FETCH_DE_COLLECT_REQUEST' // 话题取消收藏
export const FETCH_MSG_REQUEST = 'FETCH_MSG_REQUEST' // 请求消息
